{{- if index .Values "cert-manager" "enabled" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  {{- range .Values.ingress.tls }}
  name: {{ .secretName }}
  {{- end }}
spec:
  commonName: {{ .Values.environment.BW_DOMAIN }}
  {{- range .Values.ingress.tls }}
  secretName: {{ .secretName }}
  {{- end }}
  dnsNames:
    - {{ .Values.environment.BW_DOMAIN }}
  issuerRef:
    name: {{ index .Values "cert-manager" "issuerName" }}
    kind: {{ index .Values "cert-manager" "issuerKind"}}
{{- end }}    
