apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden-unified.fullname" . }}
  labels:
    {{- include "bitwarden-unified.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.environment.BW_PORT_HTTP }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.environment.BW_PORT_HTTPS }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "bitwarden-unified.selectorLabels" . | nindent 4 }}
